server:
  port: 9094

eureka:
  instance:
    hostname: localhost
    port: 9091
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000

spring:
    datasource:
        #driver-class-name: com.mysql.jdbc.Driver
        #password: '1234'
        #platform: mysql
        #url: jdbc:mysql://localhost/deliveryorder?verifyServerCertificate=false&useSSL=false&requireSSL=false
        #username: root
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/deliveryorder?verifyServerCertificate=false&useSSL=false&requireSSL=false
	      username: postgres
        password: postgres
    jpa:
        #database-platform: org.hibernate.dialect.MySQLDialect
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        generate-ddl: false
        hibernate:
            ddl-auto: create
        show-sql: true

authserver:
  hostname: http://localhost:9092
security:
  oauth2:
    resource:
      userInfoUri: ${authserver.hostname}/user
      id: payments
